/**
 * Document Templates Service
 *
 * Provides CRA compliance document templates that users can download,
 * populate with their product-specific details, and upload to their Tech File.
 *
 * Templates use {{PLACEHOLDER}} syntax for user-replaceable values.
 * The generate flow auto-populates from product/org data and marks
 * remaining fields with [REVIEW] markers.
 */

import pool from '../db/pool.js';
import { getDriver } from '../db/neo4j.js';

export interface DocumentTemplate {
  id: string;
  title: string;
  craArticle: string;
  description: string;
  techFileSection: string;
  filename: string;
}

export interface GenerateContext {
  productId: string;
  orgId: string;
  /** Optional overrides from the user */
  versionFormat?: string;
  securitySuffix?: string;
}

interface PopulatedData {
  productName: string;
  orgName: string;
  distributionModel: string;
  version: string;
  stakeholders: Record<string, { name: string; email: string }>;
}

/** Template catalogue — metadata only (no content) */
export const TEMPLATE_CATALOGUE: DocumentTemplate[] = [
  {
    id: 'versioning-security-release-policy',
    title: 'Versioning & Security Release Policy',
    craArticle: 'Article 13(9)',
    description: 'Defines how your organisation separates security updates from feature releases. Covers versioning scheme, branching strategy, security release procedure, response timelines, user communication, and evidence retention. Required to demonstrate that security patches can be deployed independently of functionality changes.',
    techFileSection: 'Art. 13 — Security Properties',
    filename: 'versioning-and-security-release-policy.md',
  },
];

/** Returns the full Markdown content for a given template ID */
export function getTemplateContent(id: string): string | null {
  const fn = templateContentMap[id];
  return fn ? fn() : null;
}

/** Generates a pre-filled template for a specific product */
export async function generateTemplateForProduct(id: string, ctx: GenerateContext): Promise<string | null> {
  const rawContent = getTemplateContent(id);
  if (!rawContent) return null;

  const data = await fetchProductData(ctx.productId, ctx.orgId);
  if (!data) return null;

  const today = new Date().toISOString().slice(0, 10);
  const deliveryModel = mapDistributionModel(data.distributionModel);
  const versionFormat = ctx.versionFormat || inferVersionFormat(data.version);
  const securitySuffix = ctx.securitySuffix || '-sec1';

  // Build the roles table from stakeholder data
  const rolesTable = buildRolesTable(data.stakeholders);

  // Replace placeholders
  let content = rawContent
    .replace(/\{\{PRODUCT_NAME\}\}/g, data.productName)
    .replace(/\{\{ORG_NAME\}\}/g, data.orgName)
    .replace(/\{\{EFFECTIVE_DATE\}\}/g, today)
    .replace(/\{\{VERSION_FORMAT\}\}/g, versionFormat)
    .replace(/\{\{SECURITY_SUFFIX\}\}/g, securitySuffix)
    .replace(/\{\{DELIVERY_MODEL\}\}/g, deliveryModel);

  // Replace the generic roles table with populated version
  content = content.replace(
    /\| Role \| Responsibility \|[\s\S]*?\| \*\*Compliance Officer\*\* \|[^\n]*\n\n> \*\*Note:\*\* Adapt the roles above to match your actual team structure\./,
    rolesTable
  );

  // Replace the instructions block header for generated documents
  content = content.replace(
    /> \*\*INSTRUCTIONS — DELETE THIS SECTION BEFORE FINALISING\*\*\n>\n> This is a template document provided by CRANIS2 to help you meet your\n> obligations under EU Cyber Resilience Act Article 13\(9\)\.\n>\n> \*\*How to use this template:\*\*\n> 1\. Replace all placeholder values[^]*?> management system as a controlled policy document\.\n>\n> \*\*Placeholders in this template:\*\*\n>[^]*?> - `\{\{DELIVERY_MODEL\}\}` — SaaS, on-premises, hybrid, embedded, etc\./,
    `> **REVIEW BEFORE FINALISING**
>
> This document was auto-generated by CRANIS2 from your product and
> organisation data. Fields marked with **[REVIEW]** need your attention.
>
> **Next steps:**
> 1. Review all sections — particularly versioning scheme, timelines,
>    and roles & responsibilities
> 2. Adjust any [REVIEW] fields to match your actual process
> 3. Have the document reviewed and approved by your Product Owner and
>    Security Lead
>
> **Where to store the completed document:**
> Paste the finalised content into your product's **Tech File** in
> CRANIS2 under the **Art. 13 — Security Properties** section.`
  );

  // Select the correct delivery model section
  if (deliveryModel.toLowerCase().includes('saas') || deliveryModel.toLowerCase().includes('hosted')) {
    // Remove on-prem section, keep SaaS
    content = content.replace(
      /> \*\*Note:\*\* Complete this section based on your delivery model \([^)]*\)\.\n\n/,
      ''
    );
    content = content.replace(
      /\*\*For on-premises \/ distributed products:\*\*\nSecurity-only releases are published[^\n]*\n[^\n]*\n/,
      ''
    );
  } else if (deliveryModel.toLowerCase().includes('on-premises') || deliveryModel.toLowerCase().includes('binary') || deliveryModel.toLowerCase().includes('embedded')) {
    // Remove SaaS section, keep on-prem
    content = content.replace(
      /> \*\*Note:\*\* Complete this section based on your delivery model \([^)]*\)\.\n\n/,
      ''
    );
    content = content.replace(
      /\*\*For SaaS products:\*\*\nUsers do not manually apply[^\n]*\n\n/,
      ''
    );
  }

  return content;
}

// ─── Data fetching ──────────────────────────────────────────────────────────────

async function fetchProductData(productId: string, orgId: string): Promise<PopulatedData | null> {
  const session = getDriver().session();
  try {
    // Fetch product and org from Neo4j
    const result = await session.run(
      `MATCH (o:Organisation {id: $orgId})<-[:BELONGS_TO]-(p:Product {id: $productId})
       RETURN p.name AS productName, p.version AS version, p.distributionModel AS distributionModel,
              o.name AS orgName`,
      { orgId, productId }
    );
    if (result.records.length === 0) return null;

    const rec = result.records[0];

    // Fetch stakeholders from Postgres
    const stakeholderResult = await pool.query(
      `SELECT role_key, name, email FROM stakeholders
       WHERE org_id = $1 AND (product_id = $2 OR product_id IS NULL)
         AND email IS NOT NULL AND email != ''
       ORDER BY product_id DESC NULLS LAST`,
      [orgId, productId]
    );

    const stakeholders: Record<string, { name: string; email: string }> = {};
    for (const row of stakeholderResult.rows) {
      // Product-level overrides org-level (ordered by product_id DESC NULLS LAST)
      if (!stakeholders[row.role_key]) {
        stakeholders[row.role_key] = { name: row.name || '', email: row.email || '' };
      }
    }

    return {
      productName: rec.get('productName') || '',
      orgName: rec.get('orgName') || '',
      distributionModel: rec.get('distributionModel') || '',
      version: rec.get('version') || '',
      stakeholders,
    };
  } finally {
    await session.close();
  }
}

// ─── Helpers ────────────────────────────────────────────────────────────────────

function mapDistributionModel(model: string): string {
  const map: Record<string, string> = {
    saas_hosted: 'SaaS (centrally hosted)',
    proprietary_binary: 'On-premises (distributed binary)',
    source_available: 'Source-available (distributed)',
    library_component: 'Library / component (distributed via package registry)',
    internal_only: 'Internal use only',
  };
  return map[model] || model || '[REVIEW: specify delivery model]';
}

function inferVersionFormat(version: string): string {
  if (!version) return '[REVIEW: e.g. MAJOR.MINOR.PATCH or YYYY.MM.DD.NNNN]';
  // Detect common patterns
  if (/^\d{4}\.\d{2}\.\d{2}/.test(version)) return 'YYYY.MM.DD.NNNN';
  if (/^\d+\.\d+\.\d+$/.test(version)) return 'MAJOR.MINOR.PATCH';
  if (/^\d+\.\d+$/.test(version)) return 'MAJOR.MINOR';
  return version + ' [REVIEW]';
}

function buildRolesTable(stakeholders: Record<string, { name: string; email: string }>): string {
  const sec = stakeholders['security_contact'];
  const mfr = stakeholders['manufacturer_contact'];
  const compliance = stakeholders['compliance_officer'];
  const techFile = stakeholders['technical_file_owner'];
  const incident = stakeholders['incident_response_lead'];

  function formatPerson(role: { name: string; email: string } | undefined, fallback: string): string {
    if (!role || (!role.name && !role.email)) return `[REVIEW: assign ${fallback}]`;
    if (role.name && role.email) return `${role.name} (${role.email})`;
    return role.name || role.email;
  }

  return `| Role | Assigned to | Responsibility |
|---|---|---|
| **Product Owner** | ${formatPerson(techFile, 'technical file owner')} | Classifies each release; approves mixed releases (exceptional cases only) |
| **Security Lead** | ${formatPerson(sec, 'security contact')} | Triages vulnerabilities; validates fix completeness; reviews security-only releases |
| **Engineering Team** | ${formatPerson(mfr, 'manufacturer contact')} | Develops fixes on isolated branches; ensures no feature code in security releases |
| **Incident Response** | ${formatPerson(incident, 'incident response lead')} | Coordinates response to actively exploited vulnerabilities; manages disclosure timeline |
| **Compliance Officer** | ${formatPerson(compliance, 'compliance officer')} | Verifies this policy is followed; maintains evidence for CRA technical file |`;
}

// ─── Template content generators ───────────────────────────────────────────────

const templateContentMap: Record<string, () => string> = {
  'versioning-security-release-policy': () => VERSIONING_POLICY_TEMPLATE,
};

// ─── Versioning & Security Release Policy ──────────────────────────────────────

const VERSIONING_POLICY_TEMPLATE = `> **INSTRUCTIONS — DELETE THIS SECTION BEFORE FINALISING**
>
> This is a template document provided by CRANIS2 to help you meet your
> obligations under EU Cyber Resilience Act Article 13(9).
>
> **How to use this template:**
> 1. Replace all placeholder values (marked with \`{{PLACEHOLDER}}\`) with
>    your product-specific details
> 2. Review and adapt each section to match your actual release process
> 3. Remove or modify any sections that do not apply to your delivery model
> 4. Have the document reviewed and approved by your Product Owner and
>    Security Lead
>
> **Where to store the completed document:**
> Once finalised, paste the content into your product's **Tech File** in
> CRANIS2 under the **Art. 13 — Security Properties** section. This
> ensures it is included in your CRA compliance evidence package and
> linked to your product's compliance status.
>
> The completed document should also be retained in your internal document
> management system as a controlled policy document.
>
> **Placeholders in this template:**
> - \`{{PRODUCT_NAME}}\` — Your product's name
> - \`{{ORG_NAME}}\` — Your organisation's name
> - \`{{EFFECTIVE_DATE}}\` — The date this policy takes effect
> - \`{{VERSION_FORMAT}}\` — Your versioning scheme (e.g. SemVer, date-based, CalVer)
> - \`{{SECURITY_SUFFIX}}\` — The suffix you use for security-only releases (e.g. -sec1, .patch1)
> - \`{{DELIVERY_MODEL}}\` — SaaS, on-premises, hybrid, embedded, etc.

---

# Versioning & Security Release Policy

**Document Owner:** Product & Engineering Lead
**Applicable Product:** {{PRODUCT_NAME}}
**Organisation:** {{ORG_NAME}}
**CRA Reference:** Article 13(9) — Separation of security and functionality updates
**Effective Date:** {{EFFECTIVE_DATE}}
**Review Cycle:** Annually, or upon significant change to the release process

---

## 1. Purpose

This policy defines how {{ORG_NAME}} distinguishes security updates from feature updates for {{PRODUCT_NAME}}, ensuring that security patches can be developed, tested, and deployed independently of functionality changes. It satisfies the requirement under EU Cyber Resilience Act Article 13(9) that manufacturers provide security updates separately from functionality updates where technically feasible.

---

## 2. Scope

This policy applies to:

- All production releases of {{PRODUCT_NAME}} (all components and services)
- All personnel involved in development, review, and deployment
- All dependencies managed within the Software Bill of Materials (SBOM)

---

## 3. Versioning Scheme

### 3.1 Format

{{PRODUCT_NAME}} uses the following versioning scheme:

\`\`\`
{{VERSION_FORMAT}}[{{SECURITY_SUFFIX}}]
\`\`\`

| Segment | Meaning |
|---|---|
| \`{{VERSION_FORMAT}}\` | Standard version identifier for the release |
| \`{{SECURITY_SUFFIX}}\` | **Security-only release suffix**. Present only when the release contains exclusively security fixes. |

### 3.2 Examples

| Version | Classification |
|---|---|
| \`1.2.0\` | Feature release (may include non-critical security improvements alongside features) |
| \`1.2.0{{SECURITY_SUFFIX}}\` | Security-only release — contains only vulnerability fixes |
| \`1.3.0\` | Feature release |
| \`1.3.0{{SECURITY_SUFFIX}}\` | Security hotfix issued against the \`1.3.0\` baseline |

> **Note:** Update the examples above to match your actual versioning scheme.

### 3.3 Classification Rules

Every release MUST be classified as one of the following:

| Classification | Definition | Version suffix |
|---|---|---|
| **Security-only** | Contains exclusively security fixes (vulnerability patches, dependency upgrades addressing CVEs, security configuration changes). No new features, no behavioural changes. | \`{{SECURITY_SUFFIX}}\` |
| **Feature** | Contains new functionality, enhancements, refactoring, or non-security bug fixes. May include minor security hardening that does not address a known vulnerability. | No suffix |
| **Mixed** | Contains both security fixes and feature changes. Mixed releases should be avoided where possible. When unavoidable, the security fixes MUST be documented separately in the release notes and the release MUST be preceded or accompanied by a security-only release containing the same fixes. | No suffix (but release notes must itemise security content) |

The **Product Owner** is responsible for classifying each release before deployment.

---

## 4. Security Release Procedure

### 4.1 Trigger

A security-only release is triggered when any of the following occur:

- A vulnerability rated **Critical** or **High** (CVSS ≥ 7.0) is identified in {{PRODUCT_NAME}} code or its dependencies
- A vulnerability rated **Medium** (CVSS 4.0–6.9) that is actively exploited or has a public exploit available
- A security advisory from a dependency maintainer recommends immediate update
- A penetration test or security audit identifies a finding requiring remediation

### 4.2 Process

\`\`\`
┌─────────────────────────────────────────────────────────────────┐
│  1. IDENTIFICATION                                              │
│     Vulnerability detected (scanner, advisory, audit, report)   │
│                           │                                     │
│  2. TRIAGE                ▼                                     │
│     Classify severity, assess exploitability, determine scope   │
│                           │                                     │
│  3. ISOLATION             ▼                                     │
│     Create hotfix branch from current production baseline       │
│     Cherry-pick or develop ONLY the security fix                │
│     No feature code included                                    │
│                           │                                     │
│  4. REVIEW & TEST         ▼                                     │
│     Code review (security-focused)                              │
│     Run full regression suite                                   │
│     Verify fix resolves the vulnerability                       │
│     Verify no functional regressions introduced                 │
│                           │                                     │
│  5. CLASSIFICATION        ▼                                     │
│     Product Owner confirms security-only classification         │
│     Version tagged with security suffix                         │
│                           │                                     │
│  6. DEPLOYMENT            ▼                                     │
│     Deploy to production via standard pipeline                  │
│     SBOM regenerated automatically                              │
│                           │                                     │
│  7. COMMUNICATION         ▼                                     │
│     Release notes published (see Section 5)                     │
│     Affected users notified                                     │
│     Changelog updated                                           │
│                           │                                     │
│  8. EVIDENCE              ▼                                     │
│     Commit history, test results, and classification archived   │
│     Vulnerability status updated in tracker                     │
└─────────────────────────────────────────────────────────────────┘
\`\`\`

### 4.3 Timelines

| Severity | Target fix deployment |
|---|---|
| Critical (CVSS ≥ 9.0) | Within 24 hours of confirmation |
| High (CVSS 7.0–8.9) | Within 72 hours of confirmation |
| Medium (CVSS 4.0–6.9, actively exploited) | Within 5 working days |
| Medium (CVSS 4.0–6.9, no known exploit) | Next scheduled release or within 30 days |
| Low (CVSS < 4.0) | Next scheduled release |

### 4.4 Independence from feature work

Security-only releases:

- **MUST NOT** include any feature changes, refactoring, or non-security bug fixes
- **MUST NOT** require users to accept new terms, configurations, or behavioural changes
- **MUST** be deployable independently of any in-progress feature work
- **MUST** be tested against the current production baseline, not a development branch

### 4.5 Branching Strategy

{{PRODUCT_NAME}} follows a branching model with a dedicated security hotfix lane. The \`main\` branch always represents the current production state.

\`\`\`
main (always = production, always deployable)
  │
  ├── feature/new-feature-name         ← new work, branched from main
  ├── feature/another-feature          ← new work, branched from main
  │
  └── sec/CVE-2026-XXXX               ← security fix, branched from main
        fix → test → merge back to main  ← deployed independently of features
        then merged forward into open feature branches
\`\`\`

#### Feature branches

1. Branch from \`main\` when starting new feature work
2. Develop and test on the feature branch
3. Merge back to \`main\` via pull request when the feature is complete, reviewed, and approved
4. Tag \`main\` with a standard version
5. Deploy from \`main\`

#### Security fix branches

1. Branch from \`main\` (the live production baseline) — name the branch \`sec/<CVE-ID>\` or \`sec/<finding-ref>\`
2. Apply **only** the security fix — no feature code, no refactoring, no unrelated changes
3. Test against the production baseline (full regression suite)
4. Merge back to \`main\` via pull request with security-focused review
5. Tag \`main\` with the security suffix (e.g. \`1.2.0{{SECURITY_SUFFIX}}\`)
6. Deploy immediately from \`main\`
7. Merge \`main\` forward into all open feature branches so they inherit the fix

#### Key principles

- **\`main\` is always deployable** — it represents exactly what is live in production
- **Security fixes never wait for feature work** — they are branched from and merged back to \`main\` independently
- **Feature branches never block security releases** — the security lane operates in parallel
- **Feature branches stay current** — after every security merge to \`main\`, open feature branches rebase or merge from \`main\` to pick up the fix
- **No mixed merges** — a security branch must not include feature commits, and vice versa

---

## 5. User Communication & Transparency

### 5.1 Release notes

Every release MUST include release notes that clearly state:

- The **classification** (Security-only, Feature, or Mixed)
- For security-only releases: the CVE identifiers or internal finding references addressed
- A plain-language summary of what was fixed and why it matters
- Whether any user action is required

### 5.2 Security update labelling

Security-only releases are identified through:

- The \`{{SECURITY_SUFFIX}}\` version suffix
- A **[SECURITY]** tag in the release notes title
- A distinct visual indicator in any update notification or changelog
- Separate grouping in the changelog (security fixes listed before feature changes)

### 5.3 Notification channels

| Channel | Used for |
|---|---|
| In-app notification / email | All security-only releases |
| Direct notification to administrators | Critical and High severity security releases |
| Changelog / release notes page | All releases |
| Status page | Releases addressing actively exploited vulnerabilities |

> **Note:** Adapt the channels above to match your actual notification infrastructure.

### 5.4 Delivery model considerations

> **Note:** Complete this section based on your delivery model ({{DELIVERY_MODEL}}).

**For SaaS products:**
Users do not manually apply updates; all releases are deployed centrally. This means users are never forced to accept feature changes in order to receive a security fix, and they are always on the latest secure version.

**For on-premises / distributed products:**
Security-only releases are published to the same distribution channel as feature releases but are clearly labelled. Users can apply security patches without upgrading to the latest feature release. Update instructions specify the minimum steps required for the security fix only.

---

## 6. Roles & Responsibilities

| Role | Responsibility |
|---|---|
| **Product Owner** | Classifies each release; approves mixed releases (exceptional cases only) |
| **Security Lead** | Triages vulnerabilities; validates fix completeness; reviews security-only releases |
| **Engineering Team** | Develops fixes on isolated branches; ensures no feature code in security releases |
| **Operations** | Deploys releases; monitors post-deployment health; triggers rollback if needed |
| **Compliance Officer** | Verifies this policy is followed; maintains evidence for CRA technical file |

> **Note:** Adapt the roles above to match your actual team structure.

---

## 7. Evidence & Audit Trail

The following artefacts are retained for each security-only release as evidence of Art. 13(9) compliance:

| Artefact | Retention |
|---|---|
| Git commit history (isolated hotfix branch) | Indefinite (version control) |
| Release classification record | Minimum 10 years (CRA support period) |
| Release notes with [SECURITY] tag | Minimum 10 years |
| Test results (regression suite) | Minimum 5 years |
| Vulnerability tracker status change | Indefinite (platform database) |
| SBOM diff (before/after) | Minimum 10 years |
| Deployment log | Minimum 5 years |

---

## 8. Policy on Mixed Releases

Mixed releases (containing both security fixes and feature changes) are **strongly discouraged**. When a mixed release is unavoidable:

1. The security fixes MUST also be available as a standalone security-only release (deployed first or concurrently)
2. The release notes MUST separately itemise all security fixes under a dedicated **Security** section
3. The Product Owner MUST document the justification for combining the changes
4. The justification is retained as part of the compliance evidence

---

## 9. Exceptions

Any deviation from this policy requires:

- Written approval from the Product Owner and Security Lead
- A documented justification explaining why the deviation was necessary
- A remediation plan to return to standard process
- Recording in the compliance evidence archive

---

## 10. Review & Revision

This policy is reviewed:

- **Annually** as part of the regular compliance review cycle
- **Upon significant change** to the release pipeline, deployment architecture, or delivery model
- **Upon regulatory guidance** from ENISA or national authorities clarifying Art. 13(9) expectations

All revisions are tracked with date, author, and summary of changes.

---

## Revision History

| Date | Author | Summary |
|---|---|---|
| {{EFFECTIVE_DATE}} | | Initial version — establishes versioning scheme, security release process, and Art. 13(9) evidence framework |
`;
