/**
 * SEE Report Generator — Phase D
 *
 * Generates structured R&D evidence reports in Markdown format.
 * Deterministic template-based generation. All statements reference
 * actual evidence from the Software Evidence Engine analysis.
 */

import pool from '../db/pool.js';
import crypto from 'crypto';
import { getLatestScan } from './see-estimator.js';
import { getCommitSummary, getDeveloperAttribution } from './see-commit-ingestor.js';
import { getBranchAnalysis } from './see-classifier.js';
import { getExperiments } from './see-experiment-detector.js';
import { logger } from '../utils/logger.js';

export interface GeneratedReport {
  id: string;
  productId: string;
  reportType: string;
  contentMd: string;
  contentHash: string;
  generatedAt: string;
}

export async function generateRnDEvidenceReport(
  productId: string,
  orgId: string,
  productName: string,
): Promise<GeneratedReport> {
  // Gather all evidence
  const [estimate, commitSummary, developers, branchAnalysis, experiments] = await Promise.all([
    getLatestScan(productId),
    getCommitSummary(productId),
    getDeveloperAttribution(productId),
    getBranchAnalysis(productId),
    getExperiments(productId),
  ]);

  const lines: string[] = [];
  const now = new Date();

  // ── Title page ────────────────────────────────────────────────────
  lines.push(`# R&D Tax Credit Evidence Report`);
  lines.push(`## ${productName}`);
  lines.push(``);
  lines.push(`**Generated:** ${now.toISOString().split('T')[0]}`);
  lines.push(`**Report type:** R&D Engineering Evidence`);
  lines.push(`**Prepared by:** CRANIS2 Software Evidence Engine`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // ── Executive summary ─────────────────────────────────────────────
  lines.push(`## 1. Executive Summary`);
  lines.push(``);

  const totalLoc = estimate?.totalLoc || 0;
  const prodLoc = estimate?.productionLoc || 0;
  const totalCommits = commitSummary?.totalCommits || 0;
  const activeMonths = commitSummary?.activeMonths || 0;
  const devCount = developers?.length || 0;
  const expCount = experiments?.uncertaintySummary?.totalExperiments || 0;
  const rewriteRatio = commitSummary?.rewriteRatio || 0;

  lines.push(`This report presents engineering evidence extracted from the source code repository of **${productName}**. The analysis covers ${totalLoc.toLocaleString()} logical lines of code, ${totalCommits.toLocaleString()} commits across ${activeMonths} active months of development by ${devCount} contributor${devCount !== 1 ? 's' : ''}.`);
  lines.push(``);

  if (expCount > 0) {
    lines.push(`The analysis identified **${expCount} indicators of technological uncertainty**, including experimentation patterns, high rewrite periods, and iterative development cycles. These indicators demonstrate that the development involved systematic investigation and resolution of technical challenges where the outcome was not readily deducible.`);
  } else {
    lines.push(`The analysis examined commit patterns, branch structures, and code evolution for indicators of technological uncertainty.`);
  }
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // ── Methodology ───────────────────────────────────────────────────
  lines.push(`## 2. Methodology`);
  lines.push(``);
  lines.push(`This report was generated by the CRANIS2 Software Evidence Engine using deterministic analysis of software development artefacts. No artificial intelligence was used in the detection of experimentation patterns or the classification of development activity. All findings reference specific, verifiable evidence in the source code repository.`);
  lines.push(``);
  lines.push(`The analysis process:`);
  lines.push(`1. **Source code measurement** — logical lines of code counted by language, excluding blank lines, comments, generated code, and vendor dependencies.`);
  lines.push(`2. **Commit history analysis** — all commits classified by type (feature, fix, refactor, test, experiment, documentation, chore) using deterministic pattern matching on commit messages.`);
  lines.push(`3. **Branch analysis** — branches classified by purpose (feature, bugfix, experiment, release) using naming conventions.`);
  lines.push(`4. **Experimentation detection** — automated identification of patterns indicating technological uncertainty: refactoring waves, rapid iteration, high rewrite ratios, prototype branches, and fix-after-feature cycles.`);
  lines.push(`5. **Developer attribution** — contribution analysis from commit authorship data.`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // ── Engineering activity summary ──────────────────────────────────
  lines.push(`## 3. Engineering Activity Summary`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total logical LOC | ${totalLoc.toLocaleString()} |`);
  lines.push(`| Production LOC | ${prodLoc.toLocaleString()} |`);
  lines.push(`| Test LOC | ${(estimate?.testLoc || 0).toLocaleString()} |`);
  lines.push(`| Total commits | ${totalCommits.toLocaleString()} |`);
  lines.push(`| Active development months | ${activeMonths} |`);
  lines.push(`| Contributors | ${devCount} |`);
  lines.push(`| Overall rewrite ratio | ${rewriteRatio}x |`);
  if (estimate?.complexityCategory) {
    lines.push(`| Complexity assessment | ${estimate.complexityCategory} (${estimate.complexityMultiplier}x) |`);
  }
  if (estimate?.effortMonths) {
    lines.push(`| Estimated effort range | ${estimate.effortMonths.low}–${estimate.effortMonths.high} engineer-months |`);
  }
  lines.push(``);

  // Commit type breakdown
  if (branchAnalysis?.commitTypes) {
    lines.push(`### Commit Classification`);
    lines.push(``);
    lines.push(`| Type | Count | Description |`);
    lines.push(`|------|-------|-------------|`);
    const typeDescriptions: Record<string, string> = {
      feature: 'New functionality development',
      fix: 'Bug fixes and corrections',
      refactor: 'Code restructuring without functional change',
      test: 'Test creation and modification',
      experiment: 'Experimental or prototype work',
      docs: 'Documentation changes',
      chore: 'Build, CI/CD, dependency updates',
      style: 'Formatting and style changes',
      other: 'Uncategorised commits',
    };
    for (const [type, count] of Object.entries(branchAnalysis.commitTypes)) {
      if ((count as number) > 0) {
        lines.push(`| ${type} | ${count} | ${typeDescriptions[type] || ''} |`);
      }
    }
    lines.push(``);
  }
  lines.push(`---`);
  lines.push(``);

  // ── Technological uncertainty indicators ───────────────────────────
  lines.push(`## 4. Technological Uncertainty Indicators`);
  lines.push(``);

  if (experiments && experiments.experiments.length > 0) {
    lines.push(`The following patterns were detected in the development history, each indicating an area where the engineering approach was not straightforward and required investigation, iteration, or reconsideration.`);
    lines.push(``);

    for (let i = 0; i < experiments.experiments.length; i++) {
      const exp = experiments.experiments[i];
      lines.push(`### 4.${i + 1}. ${exp.title}`);
      lines.push(``);
      lines.push(`**Type:** ${exp.experimentType.replace(/_/g, ' ')}`);
      lines.push(`**Confidence:** ${exp.confidence}`);
      if (exp.startDate) {
        lines.push(`**Period:** ${new Date(exp.startDate).toLocaleDateString('en-GB')}${exp.endDate ? ' – ' + new Date(exp.endDate).toLocaleDateString('en-GB') : ''}`);
      }
      lines.push(``);
      lines.push(exp.description);
      lines.push(``);
      lines.push(`**Uncertainty indicator:** ${exp.uncertaintyIndicator}`);
      lines.push(``);
      if (exp.evidenceCommits.length > 0) {
        lines.push(`**Evidence commits:** ${exp.evidenceCommits.slice(0, 5).map(s => '`' + s.slice(0, 8) + '`').join(', ')}${exp.evidenceCommits.length > 5 ? ` (and ${exp.evidenceCommits.length - 5} more)` : ''}`);
        lines.push(``);
      }
    }

    // Summary
    lines.push(`### Summary of Uncertainty Indicators`);
    lines.push(``);
    lines.push(`| Indicator type | Count | Confidence |`);
    lines.push(`|---------------|-------|-----------|`);
    for (const [type, count] of Object.entries(experiments.uncertaintySummary.byType)) {
      if ((count as number) > 0) {
        lines.push(`| ${type.replace(/_/g, ' ')} | ${count} | — |`);
      }
    }
    lines.push(`| **Total** | **${experiments.uncertaintySummary.totalExperiments}** | High: ${experiments.uncertaintySummary.highConfidence}, Medium: ${experiments.uncertaintySummary.mediumConfidence}, Low: ${experiments.uncertaintySummary.lowConfidence} |`);
    lines.push(``);
  } else {
    lines.push(`No significant experimentation patterns were detected in the commit history. This may indicate that commit history is incomplete or that development followed a straightforward path.`);
    lines.push(``);
  }
  lines.push(`---`);
  lines.push(``);

  // ── Developer attribution ─────────────────────────────────────────
  lines.push(`## 5. Developer Attribution`);
  lines.push(``);

  if (developers && developers.length > 0) {
    lines.push(`| Developer | Commits | Contribution | Active period |`);
    lines.push(`|-----------|---------|-------------|---------------|`);
    for (const dev of developers) {
      const period = dev.firstCommitAt
        ? `${new Date(dev.firstCommitAt).toLocaleDateString('en-GB', { month: 'short', year: 'numeric' })} – ${new Date(dev.lastCommitAt).toLocaleDateString('en-GB', { month: 'short', year: 'numeric' })}`
        : '–';
      lines.push(`| ${dev.authorName} | ${dev.commitCount} | ${dev.contributionPct}% | ${period} |`);
    }
    lines.push(``);
  }
  lines.push(`---`);
  lines.push(``);

  // ── Branch analysis ───────────────────────────────────────────────
  if (branchAnalysis) {
    lines.push(`## 6. Branch Analysis`);
    lines.push(``);
    lines.push(`| Branch type | Count |`);
    lines.push(`|------------|-------|`);
    for (const [type, count] of Object.entries(branchAnalysis.branchTypes)) {
      if ((count as number) > 0) {
        lines.push(`| ${type} | ${count} |`);
      }
    }
    lines.push(`| **Total** | **${branchAnalysis.totalBranches}** |`);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  // ── Conclusion ────────────────────────────────────────────────────
  lines.push(`## 7. Conclusion`);
  lines.push(``);
  lines.push(`The development of ${productName} demonstrates characteristics consistent with qualifying R&D activity:`);
  lines.push(``);
  lines.push(`- **Systematic investigation:** ${totalCommits.toLocaleString()} commits across ${activeMonths} months of structured development.`);
  if (expCount > 0) {
    lines.push(`- **Technological uncertainty:** ${expCount} detected patterns of experimentation, iteration, and approach reconsideration.`);
  }
  if (rewriteRatio > 0.3) {
    lines.push(`- **Iterative resolution:** A rewrite ratio of ${rewriteRatio}x indicates that solutions were not immediately apparent and required revision.`);
  }
  lines.push(`- **Competent professionals:** ${devCount} contributor${devCount !== 1 ? 's' : ''} with demonstrated engineering capability.`);
  lines.push(``);
  lines.push(`This evidence supports the claim that the development work involved the resolution of technological uncertainty through systematic investigation by competent professionals.`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`## 8. Caveats`);
  lines.push(``);
  lines.push(`- This report is based on automated analysis of repository artefacts. It does not replace professional R&D tax advisory services.`);
  lines.push(`- Commit classification uses deterministic pattern matching on commit messages. Miscategorised commits may affect the analysis.`);
  lines.push(`- The absence of detected experimentation does not mean no R&D occurred. Some development activities may not leave clear patterns in commit history.`);
  lines.push(`- Developer attribution is based on commit authorship. Pair programming, code review, and non-coding contributions are not captured.`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);
  lines.push(`*Generated by CRANIS2 Software Evidence Engine. All findings reference verifiable repository data.*`);

  const contentMd = lines.join('\n');
  const contentHash = crypto.createHash('sha256').update(contentMd).digest('hex');

  // Store the report
  const insertResult = await pool.query(
    `INSERT INTO see_evidence_reports (product_id, org_id, report_type, content_md, content_hash)
     VALUES ($1, $2, 'rnd_tax', $3, $4) RETURNING id, generated_at`,
    [productId, orgId, contentMd, contentHash]
  );

  const row = insertResult.rows[0];

  logger.info(`[SEE] Generated R&D evidence report for product ${productId}, hash ${contentHash.slice(0, 12)}`);

  return {
    id: row.id,
    productId,
    reportType: 'rnd_tax',
    contentMd,
    contentHash,
    generatedAt: row.generated_at,
  };
}

export async function getLatestReport(productId: string, reportType: string = 'rnd_tax'): Promise<GeneratedReport | null> {
  const result = await pool.query(
    `SELECT * FROM see_evidence_reports
     WHERE product_id = $1 AND report_type = $2
     ORDER BY generated_at DESC LIMIT 1`,
    [productId, reportType]
  );
  if (result.rows.length === 0) return null;
  const r = result.rows[0];
  return {
    id: r.id,
    productId: r.product_id,
    reportType: r.report_type,
    contentMd: r.content_md,
    contentHash: r.content_hash,
    generatedAt: r.generated_at,
  };
}
