import { Router, Request, Response } from 'express';
import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';
import { getDriver } from '../../db/neo4j.js';
import pool from '../../db/pool.js';
import { requireAuth, getUserOrgId, ensureSections } from './shared.js';

const router = Router();

interface CvdPdfData {
  productName: string;
  orgName: string;
  orgCountry: string | null;
  securityContactName: string;
  securityContactEmail: string;
  reportingContact: string;
  updateMechanism: string;
  supportPeriodEnd: string | null;
  isDraft: boolean;
  dateStr: string;
}

function generateCvdPolicyPdf(data: CvdPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 60, size: 'A4' });
    const chunks: Buffer[] = [];
    const stream = new PassThrough();

    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
    doc.pipe(stream);

    const pageWidth = doc.page.width - 120;
    const navy = '#003399';
    const bodyColour = '#111827';
    const mutedColour = '#6b7280';

    // EU-blue top and bottom border bars
    doc.rect(0, 0, doc.page.width, 10).fill(navy);
    doc.rect(0, doc.page.height - 10, doc.page.width, 10).fill(navy);

    // DRAFT watermark
    if (data.isDraft) {
      doc.save();
      doc.opacity(0.07);
      doc.fontSize(100).fillColor('#9ca3af').text('DRAFT', 60, 250, { align: 'center', width: pageWidth, lineBreak: false });
      doc.restore();
    }

    function addFooter() {
      const bottom = doc.page.height - 28;
      doc.save();
      doc.fontSize(8).fillColor(mutedColour);
      doc.text(
        `CVD Policy – generated by CRANIS2 – ${new Date().toLocaleDateString('en-GB')}`,
        60, bottom, { width: pageWidth, align: 'center', lineBreak: false }
      );
      doc.restore();
    }

    // ── Header ──
    doc.y = 28;
    doc.fontSize(8).fillColor(mutedColour).font('Helvetica')
      .text('REGULATION (EU) 2024/2847 – CYBER RESILIENCE ACT', 60, doc.y, { align: 'center', width: pageWidth });
    doc.moveDown(0.4);
    doc.fontSize(18).fillColor(navy).font('Helvetica-Bold')
      .text('COORDINATED VULNERABILITY', 60, doc.y, { align: 'center', width: pageWidth });
    doc.moveDown(0.15);
    doc.fontSize(18).fillColor(navy).font('Helvetica-Bold')
      .text('DISCLOSURE POLICY', 60, doc.y, { align: 'center', width: pageWidth });
    doc.font('Helvetica');
    doc.moveDown(0.3);

    if (data.isDraft) {
      doc.fontSize(10).fillColor('#b45309')
        .text('[ DRAFT – Not yet finalised ]', 60, doc.y, { align: 'center', width: pageWidth });
      doc.moveDown(0.2);
    }

    doc.fontSize(10).fillColor(bodyColour)
      .text(`${data.productName}  –  ${data.orgName}`, 60, doc.y, { align: 'center', width: pageWidth });
    doc.moveDown(0.5);
    doc.moveTo(60, doc.y).lineTo(60 + pageWidth, doc.y).strokeColor(navy).lineWidth(1.5).stroke();
    doc.moveDown(0.8);

    // ── Numbered sections ──
    function section(num: string, heading: string, body: string) {
      doc.moveDown(0.4);
      doc.fontSize(10).fillColor(navy).font('Helvetica-Bold')
        .text(`${num}.  ${heading}`, 60, doc.y, { lineGap: 2, width: pageWidth });
      doc.font('Helvetica').fontSize(9.5).fillColor(bodyColour)
        .text(body, 80, doc.y, { lineGap: 3, width: pageWidth - 20 });
    }

    section('1', 'Introduction',
      `${data.orgName} is committed to the security of ${data.productName}. We welcome and encourage ` +
      `security researchers to report vulnerabilities they discover. This Coordinated Vulnerability ` +
      `Disclosure (CVD) policy describes how to report vulnerabilities to us, what to expect in ` +
      `return, and our commitment to responsible handling of reported issues.\n\n` +
      `This policy is established in accordance with Article 13(6) and Annex I, Part II of the ` +
      `EU Cyber Resilience Act (Regulation (EU) 2024/2847).`);

    section('2', 'Scope',
      `This policy applies to ${data.productName} and all associated components, libraries, ` +
      `and services distributed or maintained by ${data.orgName}.`);

    const contactInfo = data.securityContactEmail || data.reportingContact || '[security contact to be confirmed]';
    section('3', 'How to Report a Vulnerability',
      `Please report security vulnerabilities to:\n\n` +
      `    ${contactInfo}` +
      (data.securityContactName ? `\n    Contact: ${data.securityContactName}` : '') +
      `\n\nWhen reporting, please include:\n` +
      `  \u2022  A description of the vulnerability and its potential impact\n` +
      `  \u2022  Step-by-step instructions to reproduce the issue\n` +
      `  \u2022  The affected version(s) of ${data.productName}\n` +
      `  \u2022  Any proof-of-concept code (if available)\n` +
      `  \u2022  Your preferred contact details for follow-up\n\n` +
      `Please do not report security vulnerabilities through public issue trackers.`);

    section('4', 'What to Expect',
      `Upon receiving your report, we will:\n\n` +
      `  \u2022  Acknowledge receipt within 5 business days\n` +
      `  \u2022  Provide an initial assessment within 15 business days\n` +
      `  \u2022  Work with you to understand and validate the finding\n` +
      `  \u2022  Develop and test a fix\n` +
      `  \u2022  Coordinate public disclosure within 90 days of the initial report\n\n` +
      `We may adjust the 90-day disclosure timeline if the vulnerability is particularly complex ` +
      `or if a fix requires coordination with third parties. We will keep you informed of progress throughout.`);

    section('5', 'Our Commitment',
      `  \u2022  We will not pursue legal action against researchers who report vulnerabilities ` +
      `in good faith and in accordance with this policy.\n` +
      `  \u2022  We will credit researchers in security advisories unless anonymity is requested.\n` +
      `  \u2022  We will provide timely security updates free of charge for the duration of the ` +
      `support period.\n` +
      `  \u2022  We will distribute security updates separately from feature updates where ` +
      `technically feasible.`);

    const mechanism = data.updateMechanism || 'Security updates will be distributed through the product\'s standard update channel.';
    section('6', 'Security Update Distribution', mechanism);

    if (data.supportPeriodEnd) {
      section('7', 'Support Period',
        `${data.orgName} will provide security updates and vulnerability handling for ` +
        `${data.productName} until ${data.supportPeriodEnd}. After this date, the product ` +
        `will no longer receive security updates.`);
    } else {
      section('7', 'Support Period',
        `${data.orgName} will provide security updates and vulnerability handling for ` +
        `${data.productName} for a minimum of 5 years from the date of market placement, ` +
        `in accordance with CRA Article 13(6). The specific end date will be communicated ` +
        `in the product documentation.`);
    }

    section('8', 'Safe Harbour',
      `${data.orgName} considers security research conducted in accordance with this policy ` +
      `to be authorised. We will not initiate or support legal proceedings against researchers ` +
      `who make a good-faith effort to comply with this policy.\n\n` +
      `If legal action is initiated by a third party against a researcher for activities that ` +
      `were conducted in accordance with this policy, we will make this authorisation known.`);

    // ── Signature block ──
    doc.moveDown(1.5);
    doc.moveTo(60, doc.y).lineTo(60 + pageWidth, doc.y).strokeColor('#d1d5db').lineWidth(0.5).stroke();
    doc.moveDown(0.8);

    doc.fontSize(10).fillColor(navy).font('Helvetica-Bold').text('Issued by:', 60, doc.y, { width: pageWidth });
    doc.font('Helvetica').fillColor(bodyColour).text(data.orgName, 80, doc.y, { width: pageWidth - 20 });
    if (data.orgCountry) doc.text(data.orgCountry, 80, doc.y, { width: pageWidth - 20 });

    doc.moveDown(0.6);
    doc.fontSize(10).fillColor(navy).font('Helvetica-Bold').text('Effective date:', 60, doc.y, { width: pageWidth });
    doc.font('Helvetica').fillColor(bodyColour).text(data.dateStr, 80, doc.y, { width: pageWidth - 20 });

    doc.moveDown(1.5);
    doc.moveTo(60, doc.y).lineTo(260, doc.y).strokeColor(bodyColour).lineWidth(0.5).stroke();
    doc.moveDown(0.3);
    doc.fontSize(9).fillColor(mutedColour).text('Authorised signatory', 60, doc.y);

    addFooter();
    doc.end();
  });
}

// ─── GET /api/technical-file/:productId/cvd-policy/pdf ────────────
router.get('/:productId/cvd-policy/pdf', requireAuth, async (req: Request, res: Response) => {
  const userId = (req as any).userId;
  const orgId = await getUserOrgId(userId);
  if (!orgId) { res.status(403).json({ error: 'No organisation found' }); return; }

  const productId = req.params.productId as string;

  // Verify product belongs to org and fetch product + org data
  const neo4jSession = getDriver().session();
  let productName: string;
  let orgName: string;
  let orgCountry: string | null;

  try {
    const result = await neo4jSession.run(
      `MATCH (o:Organisation {id: $orgId})<-[:BELONGS_TO]-(p:Product {id: $productId})
       RETURN p.name AS name, o.name AS orgName, o.country AS orgCountry`,
      { orgId, productId }
    );
    if (result.records.length === 0) {
      res.status(404).json({ error: 'Product not found' });
      return;
    }
    const rec = result.records[0];
    productName = rec.get('name') || productId;
    orgName = rec.get('orgName') || 'Unknown Organisation';
    orgCountry = rec.get('orgCountry') || null;
  } finally {
    await neo4jSession.close();
  }

  // Fetch sections + stakeholders in parallel
  await ensureSections(productId);

  const [sectResult, stakeholderResult] = await Promise.all([
    pool.query(
      `SELECT section_key, content, status
       FROM technical_file_sections
       WHERE product_id = $1 AND section_key IN ('vulnerability_handling', 'support_period')`,
      [productId]
    ),
    pool.query(
      `SELECT role_key, name, email FROM stakeholders
       WHERE org_id = $1 AND (product_id = $2 OR product_id IS NULL)
         AND role_key IN ('security_contact', 'manufacturer_contact')
         AND email IS NOT NULL AND email != ''
       ORDER BY product_id DESC NULLS LAST`,
      [orgId, productId]
    ),
  ]);

  let reportingContact = '';
  let updateMechanism = '';
  let vulnHandlingStatus = 'not_started';
  let supportPeriodEnd: string | null = null;

  for (const row of sectResult.rows) {
    const content = typeof row.content === 'string' ? JSON.parse(row.content) : row.content;
    const fields = content.fields || content;
    if (row.section_key === 'vulnerability_handling') {
      reportingContact = fields.reporting_contact || '';
      updateMechanism = fields.update_distribution_mechanism || '';
      vulnHandlingStatus = row.status;
    } else if (row.section_key === 'support_period') {
      supportPeriodEnd = fields.end_date || null;
      if (supportPeriodEnd) {
        try {
          supportPeriodEnd = new Date(supportPeriodEnd).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
        } catch { /* keep raw string */ }
      }
    }
  }

  // Find best security contact
  let securityContactName = '';
  let securityContactEmail = '';
  for (const row of stakeholderResult.rows) {
    if (row.role_key === 'security_contact') {
      securityContactName = row.name || '';
      securityContactEmail = row.email || '';
      break;
    }
  }
  // Fall back to manufacturer contact if no security contact
  if (!securityContactEmail) {
    for (const row of stakeholderResult.rows) {
      if (row.role_key === 'manufacturer_contact') {
        securityContactName = row.name || '';
        securityContactEmail = row.email || '';
        break;
      }
    }
  }

  const isDraft = vulnHandlingStatus !== 'completed';
  const dateStr = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  const safeName = productName.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  const filename = `cvd-policy-${safeName}-${new Date().toISOString().slice(0, 10)}.pdf`;

  try {
    const pdf = await generateCvdPolicyPdf({
      productName, orgName, orgCountry,
      securityContactName, securityContactEmail,
      reportingContact, updateMechanism, supportPeriodEnd,
      isDraft, dateStr,
    });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(pdf);
  } catch (err) {
    console.error('Failed to generate CVD policy PDF:', err);
    res.status(500).json({ error: 'Failed to generate CVD policy PDF' });
  }
});

export default router;
