import { Router, Request, Response } from 'express';
import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';
import { getDriver } from '../../db/neo4j.js';
import pool from '../../db/pool.js';
import { requireAuth, getUserOrgId, ensureSections, formatCraCategory } from './shared.js';

const router = Router();

interface DocPdfData {
  productName: string;
  productCraCategory: string | null;
  orgName: string;
  orgCountry: string | null;
  docFields: Record<string, string>;
  standardsList: any[];
  isDraft: boolean;
  dateStr: string;
}

function generateDocPdf(data: DocPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 60, size: 'A4' });
    const chunks: Buffer[] = [];
    const stream = new PassThrough();

    stream.on('data', (chunk: Buffer) => chunks.push(chunk));
    stream.on('end', () => resolve(Buffer.concat(chunks)));
    stream.on('error', reject);
    doc.pipe(stream);

    const pageWidth = doc.page.width - 120;
    const navy = '#003399';
    const bodyColour = '#111827';
    const mutedColour = '#6b7280';
    const draftColour = '#b45309';

    // EU-blue top and bottom border bars
    doc.rect(0, 0, doc.page.width, 10).fill(navy);
    doc.rect(0, doc.page.height - 10, doc.page.width, 10).fill(navy);

    // DRAFT watermark
    if (data.isDraft) {
      doc.save();
      doc.opacity(0.07);
      doc.fontSize(100).fillColor('#9ca3af').text('DRAFT', 60, 250, { align: 'center', width: pageWidth, lineBreak: false });
      doc.restore();
    }

    // Footer
    function addFooter() {
      const bottom = doc.page.height - 28;
      doc.save();
      doc.fontSize(8).fillColor(mutedColour);
      doc.text(
        `EU Declaration of Conformity – generated by CRANIS2 – ${new Date().toLocaleDateString('en-GB')}`,
        60, bottom, { width: pageWidth, align: 'center', lineBreak: false }
      );
      doc.restore();
    }

    // ── Header ──
    doc.y = 28;
    doc.fontSize(8).fillColor(mutedColour).font('Helvetica')
      .text('REGULATION (EU) 2024/2847 – CYBER RESILIENCE ACT', 60, doc.y, { align: 'center', width: pageWidth });
    doc.moveDown(0.4);
    doc.fontSize(18).fillColor(navy).font('Helvetica-Bold')
      .text('EU DECLARATION OF CONFORMITY', 60, doc.y, { align: 'center', width: pageWidth });
    doc.font('Helvetica');
    doc.moveDown(0.3);

    if (data.isDraft) {
      doc.fontSize(10).fillColor(draftColour)
        .text('[ DRAFT – Not yet finalised ]', 60, doc.y, { align: 'center', width: pageWidth });
      doc.moveDown(0.2);
    }

    if (data.docFields.certificate_reference) {
      doc.fontSize(9).fillColor(mutedColour)
        .text(`No. ${data.docFields.certificate_reference}`, 60, doc.y, { align: 'center', width: pageWidth });
      doc.moveDown(0.2);
    }

    doc.moveDown(0.5);
    doc.moveTo(60, doc.y).lineTo(60 + pageWidth, doc.y).strokeColor(navy).lineWidth(1.5).stroke();
    doc.moveDown(0.8);

    // ── Numbered clauses ──
    function clause(num: string, heading: string, body: string) {
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor(navy).font('Helvetica-Bold')
        .text(`${num}.  ${heading}`, 60, doc.y, { lineGap: 2, width: pageWidth });
      doc.font('Helvetica').fontSize(10).fillColor(bodyColour)
        .text(body, 80, doc.y, { lineGap: 3, width: pageWidth - 20 });
    }

    clause('1', 'Product name and type', data.productName);

    const mfgLine = `${data.orgName}${data.orgCountry ? ', ' + data.orgCountry : ''}`;
    clause('2', 'Manufacturer name and address', mfgLine);

    clause('3', 'Responsibility',
      'This declaration of conformity is issued under the sole responsibility of the manufacturer.');

    clause('4', 'Object of the declaration',
      `${data.productName} (CRA Category: ${formatCraCategory(data.productCraCategory)})`);

    clause('5', 'Legislative basis',
      'The object of the declaration described above is in conformity with the relevant Union harmonisation legislation:\n\n' +
      'Regulation (EU) 2024/2847 of the European Parliament and of the Council of 23 October 2024 ' +
      'on horizontal cybersecurity requirements for products with digital elements (Cyber Resilience Act) ' +
      'and its national implementing measures.');

    const standardsText = data.standardsList.length > 0
      ? data.standardsList.map((s: any) => {
          const name = typeof s === 'string' ? s : (s.name || s.reference || s.id || JSON.stringify(s));
          return `\u2022 ${name}`;
        }).join('\n')
      : 'No harmonised standards specified. See Technical File, Section 5 for the full standards assessment.';
    clause('6', 'Harmonised standards and technical specifications', standardsText);

    if (data.docFields.notified_body) {
      const nbText = data.docFields.notified_body +
        (data.docFields.certificate_reference ? `\nCertificate reference: ${data.docFields.certificate_reference}` : '');
      clause('7', 'Notified body (where applicable)', nbText);
    }

    if (data.docFields.declaration_text) {
      clause('8', 'Additional information', data.docFields.declaration_text);
    }

    if (data.docFields.assessment_module) {
      doc.moveDown(0.5);
      doc.fontSize(10).fillColor(navy).font('Helvetica-Bold')
        .text('Conformity assessment procedure:', 60, doc.y, { width: pageWidth });
      doc.font('Helvetica').fillColor(bodyColour)
        .text(`Module ${data.docFields.assessment_module}`, 80, doc.y, { width: pageWidth - 20 });
    }

    // ── Signature block ──
    doc.moveDown(1.5);
    doc.moveTo(60, doc.y).lineTo(60 + pageWidth, doc.y).strokeColor('#d1d5db').lineWidth(0.5).stroke();
    doc.moveDown(0.8);

    doc.fontSize(10).fillColor(navy).font('Helvetica-Bold').text('Signed for and on behalf of:', 60, doc.y, { width: pageWidth });
    doc.font('Helvetica').fillColor(bodyColour).text(data.orgName, 80, doc.y, { width: pageWidth - 20 });
    if (data.orgCountry) doc.text(data.orgCountry, 80, doc.y, { width: pageWidth - 20 });

    doc.moveDown(0.6);
    doc.fontSize(10).fillColor(navy).font('Helvetica-Bold').text('Place and date of issue:', 60, doc.y, { width: pageWidth });
    doc.font('Helvetica').fillColor(bodyColour)
      .text(data.dateStr + (data.orgCountry ? `, ${data.orgCountry}` : ''), 80, doc.y, { width: pageWidth - 20 });

    doc.moveDown(1.5);
    doc.moveTo(60, doc.y).lineTo(260, doc.y).strokeColor(bodyColour).lineWidth(0.5).stroke();
    doc.moveDown(0.3);
    doc.fontSize(9).fillColor(mutedColour).text('Authorised signatory', 60, doc.y);

    addFooter();
    doc.end();
  });
}

// ─── GET /api/technical-file/:productId/declaration-of-conformity/pdf ──
router.get('/:productId/declaration-of-conformity/pdf', requireAuth, async (req: Request, res: Response) => {
  const userId = (req as any).userId;
  const orgId = await getUserOrgId(userId);
  if (!orgId) { res.status(403).json({ error: 'No organisation found' }); return; }

  const productId = req.params.productId as string;

  // Verify product belongs to org and fetch product + org data
  const neo4jSession = getDriver().session();
  let productName: string;
  let productCraCategory: string | null;
  let orgName: string;
  let orgCountry: string | null;

  try {
    const result = await neo4jSession.run(
      `MATCH (o:Organisation {id: $orgId})<-[:BELONGS_TO]-(p:Product {id: $productId})
       RETURN p.name AS name, p.craCategory AS craCategory,
              o.name AS orgName, o.country AS orgCountry`,
      { orgId, productId }
    );
    if (result.records.length === 0) {
      res.status(404).json({ error: 'Product not found' });
      return;
    }
    const rec = result.records[0];
    productName = rec.get('name') || productId;
    productCraCategory = rec.get('craCategory') || null;
    orgName = rec.get('orgName') || 'Unknown Organisation';
    orgCountry = rec.get('orgCountry') || null;
  } finally {
    await neo4jSession.close();
  }

  // Fetch DoC section and standards (auto-create sections if needed)
  await ensureSections(productId);

  const sectResult = await pool.query(
    `SELECT section_key, content, status
     FROM technical_file_sections
     WHERE product_id = $1 AND section_key IN ('declaration_of_conformity', 'standards_applied')`,
    [productId]
  );

  let docFields: Record<string, string> = {};
  let docStatus = 'not_started';
  let standardsList: any[] = [];

  for (const row of sectResult.rows) {
    const content = typeof row.content === 'string' ? JSON.parse(row.content) : row.content;
    if (row.section_key === 'declaration_of_conformity') {
      docFields = content.fields || {};
      docStatus = row.status;
    } else if (row.section_key === 'standards_applied') {
      standardsList = content.standards || [];
    }
  }

  const isDraft = docStatus !== 'completed';
  const ceDate = docFields.ce_marking_date;
  const dateStr = ceDate
    ? new Date(ceDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    : new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  const safeName = productName.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  const filename = `eu-declaration-of-conformity-${safeName}-${new Date().toISOString().slice(0, 10)}.pdf`;

  try {
    const pdf = await generateDocPdf({ productName, productCraCategory, orgName, orgCountry, docFields, standardsList, isDraft, dateStr });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(pdf);
  } catch (err) {
    console.error('Failed to generate EU DoC PDF:', err);
    res.status(500).json({ error: 'Failed to generate EU Declaration of Conformity' });
  }
});

export default router;
