import { Router, Request, Response } from 'express';
import { getDriver } from '../../db/neo4j.js';
import pool from '../../db/pool.js';
import { requireAuth, getUserOrgId, ensureSections, formatCraCategory } from './shared.js';

const router = Router();

interface DocData {
  productName: string;
  productCraCategory: string | null;
  orgName: string;
  orgCountry: string | null;
  docFields: Record<string, string>;
  standardsList: any[];
  isDraft: boolean;
  dateStr: string;
}

function generateDocMarkdown(data: DocData): string {
  const lines: string[] = [];

  lines.push('REGULATION (EU) 2024/2847 — CYBER RESILIENCE ACT');
  lines.push('');
  lines.push('# EU DECLARATION OF CONFORMITY');
  lines.push('');

  if (data.isDraft) {
    lines.push('> **DRAFT — Not yet finalised**');
    lines.push('');
  }

  if (data.docFields.certificate_reference) {
    lines.push(`No. ${data.docFields.certificate_reference}`);
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  // Clause 1
  lines.push('## 1. Product name and type');
  lines.push('');
  lines.push(data.productName);
  lines.push('');

  // Clause 2
  lines.push('## 2. Manufacturer name and address');
  lines.push('');
  lines.push(`${data.orgName}${data.orgCountry ? ', ' + data.orgCountry : ''}`);
  lines.push('');

  // Clause 3
  lines.push('## 3. Responsibility');
  lines.push('');
  lines.push('This declaration of conformity is issued under the sole responsibility of the manufacturer.');
  lines.push('');

  // Clause 4
  lines.push('## 4. Object of the declaration');
  lines.push('');
  lines.push(`${data.productName} (CRA Category: ${formatCraCategory(data.productCraCategory)})`);
  lines.push('');

  // Clause 5
  lines.push('## 5. Legislative basis');
  lines.push('');
  lines.push(
    'The object of the declaration described above is in conformity with the relevant Union harmonisation legislation:'
  );
  lines.push('');
  lines.push(
    'Regulation (EU) 2024/2847 of the European Parliament and of the Council of 23 October 2024 ' +
    'on horizontal cybersecurity requirements for products with digital elements (Cyber Resilience Act) ' +
    'and its national implementing measures.'
  );
  lines.push('');

  // Clause 6
  lines.push('## 6. Harmonised standards and technical specifications');
  lines.push('');
  if (data.standardsList.length > 0) {
    for (const s of data.standardsList) {
      const name = typeof s === 'string' ? s : (s.name || s.reference || s.id || JSON.stringify(s));
      lines.push(`- ${name}`);
    }
  } else {
    lines.push('No harmonised standards specified. See Technical File, Section 5 for the full standards assessment.');
  }
  lines.push('');

  // Clause 7
  if (data.docFields.notified_body) {
    lines.push('## 7. Notified body (where applicable)');
    lines.push('');
    lines.push(data.docFields.notified_body);
    if (data.docFields.certificate_reference) {
      lines.push(`Certificate reference: ${data.docFields.certificate_reference}`);
    }
    lines.push('');
  }

  // Clause 8
  if (data.docFields.declaration_text) {
    lines.push('## 8. Additional information');
    lines.push('');
    lines.push(data.docFields.declaration_text);
    lines.push('');
  }

  // Assessment module
  if (data.docFields.assessment_module) {
    lines.push('**Conformity assessment procedure:** Module ' + data.docFields.assessment_module);
    lines.push('');
  }

  // Signature block
  lines.push('---');
  lines.push('');
  lines.push(`**Signed for and on behalf of:** ${data.orgName}`);
  if (data.orgCountry) lines.push(`${data.orgCountry}`);
  lines.push('');
  lines.push(`**Place and date of issue:** ${data.dateStr}${data.orgCountry ? ', ' + data.orgCountry : ''}`);
  lines.push('');
  lines.push('');
  lines.push('_________________________');
  lines.push('Authorised signatory');
  lines.push('');
  lines.push('---');
  lines.push(`*EU Declaration of Conformity — generated by CRANIS2 — ${new Date().toLocaleDateString('en-GB')}*`);

  return lines.join('\n');
}

// ─── GET /api/technical-file/:productId/declaration-of-conformity/pdf ──
router.get('/:productId/declaration-of-conformity/pdf', requireAuth, async (req: Request, res: Response) => {
  const userId = (req as any).userId;
  const orgId = await getUserOrgId(userId);
  if (!orgId) { res.status(403).json({ error: 'No organisation found' }); return; }

  const productId = req.params.productId as string;

  // Verify product belongs to org and fetch product + org data
  const neo4jSession = getDriver().session();
  let productName: string;
  let productCraCategory: string | null;
  let orgName: string;
  let orgCountry: string | null;

  try {
    const result = await neo4jSession.run(
      `MATCH (o:Organisation {id: $orgId})<-[:BELONGS_TO]-(p:Product {id: $productId})
       RETURN p.name AS name, p.craCategory AS craCategory,
              o.name AS orgName, o.country AS orgCountry`,
      { orgId, productId }
    );
    if (result.records.length === 0) {
      res.status(404).json({ error: 'Product not found' });
      return;
    }
    const rec = result.records[0];
    productName = rec.get('name') || productId;
    productCraCategory = rec.get('craCategory') || null;
    orgName = rec.get('orgName') || 'Unknown Organisation';
    orgCountry = rec.get('orgCountry') || null;
  } finally {
    await neo4jSession.close();
  }

  // Fetch DoC section and standards (auto-create sections if needed)
  await ensureSections(productId);

  const sectResult = await pool.query(
    `SELECT section_key, content, status
     FROM technical_file_sections
     WHERE product_id = $1 AND section_key IN ('declaration_of_conformity', 'standards_applied')`,
    [productId]
  );

  let docFields: Record<string, string> = {};
  let docStatus = 'not_started';
  let standardsList: any[] = [];

  for (const row of sectResult.rows) {
    const content = typeof row.content === 'string' ? JSON.parse(row.content) : row.content;
    if (row.section_key === 'declaration_of_conformity') {
      docFields = content.fields || {};
      docStatus = row.status;
    } else if (row.section_key === 'standards_applied') {
      standardsList = content.standards || [];
    }
  }

  const isDraft = docStatus !== 'completed';
  const ceDate = docFields.ce_marking_date;
  const dateStr = ceDate
    ? new Date(ceDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
    : new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  const safeName = productName.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  const filename = `eu-declaration-of-conformity-${safeName}-${new Date().toISOString().slice(0, 10)}.md`;

  try {
    const md = generateDocMarkdown({ productName, productCraCategory, orgName, orgCountry, docFields, standardsList, isDraft, dateStr });
    res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.send(md);
  } catch (err) {
    console.error('Failed to generate EU DoC:', err);
    res.status(500).json({ error: 'Failed to generate EU Declaration of Conformity' });
  }
});

export default router;
